on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dzbuild.azurecr.io
        username: ${{ secrets.acr_dzbuild_username }}
        password: ${{ secrets.acr_dzbuild_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dzbuild.azurecr.io/ksec3:${{ github.sha }}
        docker push dzbuild.azurecr.io/ksec3:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ksec3_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ksec39ad4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ksec39ad4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ksec39ad4
        container-registry-url: dzbuild.azurecr.io
        container-registry-username: ${{ secrets.acr_dzbuild_username }}
        container-registry-password: ${{ secrets.acr_dzbuild_password }}
        secret-name: ksec3dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: ksec39ad4
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          dzbuild.azurecr.io/ksec3:${{ github.sha }}
        imagepullsecrets: |
          ksec3dockerauth