on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dzbuild.azurecr.io
        username: ${{ secrets.acr_dzbuild_username }}
        password: ${{ secrets.acr_dzbuild_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dzbuild.azurecr.io/policy15:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dzbuild.azurecr.io/policy15:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_policy15_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep policy158be2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace policy158be2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: policy158be2
        container-registry-url: dzbuild.azurecr.io
        container-registry-username: ${{ secrets.acr_dzbuild_username }}
        container-registry-password: ${{ secrets.acr_dzbuild_password }}
        secret-name: policy15dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: policy158be2
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          dzbuild.azurecr.io/policy15:${{ github.sha }}
        imagepullsecrets: |
          policy15dockerauth
